import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics',
      items: [
        'ros2-fundamentals',
        'ai-agents-and-ros2',
        'humanoid-modeling-with-urdf',
      ],
    },
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics Module 2',
      items: [
        'digital-twins-and-gazebo',
        'unity-for-interaction',
        'sensor-simulation',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'nvidia-isaac-sim',
        'isaac-ros-and-perception',
        'navigation-with-nav2',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'vision-language-action-systems',
        'voice-and-language-to-action',
        'autonomous-humanoid-capstone',
      ],
    },
  ],
};

export default sidebars;
